---
name: Deploy Docker Image

on: push
#  push:
#    tags:
#      - v.*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract tag name
        id: tag_name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: gcr.io/rubenqba/inegi:${{github.sha}} #${{ env.TAG_NAME }}
          build-args: |
            ARG1_NAME=arg1_value
            ARG2_NAME=arg2_value
          github-token: ${{ github.token }}
