name: Maven Release

on:
  push:
    branches:
      - master

jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Asegúrate de usar la versión que tu proyecto requiere
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Check tests
        run: mvn -B release:prepare release:perform --file pom.xml -Darguments='-DskipTests'
